id: P008240
initial_creation_type: ocr
source_metadata:
  id: bdr:W20571
  title: བསྡུས་གཞུང་ལུང་རིགས་ཉི་མའི་ཟུར་བཀོལ་སོགས་ཉེར་མཁོའི་ཡིག་ཆ་སྐོར་ཞིག
  author: ''
  volumes:
    b7c5c1ba13e34fea973f615de795c5f0:
      image_group_id: I1PD30392
      title: ''
      volume_number: 1
      total_pages: 638
      base_file: v001.txt
