id: I7CEE3D0D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:50:40+00:00'
last_modified: '2022-06-08T08:10:07.854810+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20571
  title: བསྡུས་གཞུང་ལུང་རིགས་ཉི་མའི་ཟུར་བཀོལ་སོགས་ཉེར་མཁོའི་ཡིག་ཆ་སྐོར་ཞིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6848':
      image_group_id: I1PD30392
      title: ''
      total_pages: 638
      order: 1
      base_file: 6848.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
